language: java
notifications:
  hipchat:
    rooms:
      secure: l+qFKnfFcysPPPwftNvTYVUqQNkAPez+9xZB62S38Y6F6wtDSq+ROQE5nFCCT1F6g2qFY/kuZOQvXmBF6ohS+9ShSVcxvuyCgw2/WQgWKMkrQGKrZmYfki3Vmm9HpPFFOfVhzdgHluaN4MxZbaJFNzI/hdqJRUYzg69J6hpYA+j8hPnLnAk2Y6t+UvCtEo0g7wmRDbrtHyxq9MTwhYQxJyTjJKaIX5hb1d4ZlJxOwB6MR/kJThFSdFrd8UWrLtUb5hAyJzOZWodHsurNz/1mPOnH7WhuUaz6yhKsnprN5vTalQRa/qNIgnBLk1uPCKiRTzYXdiuEZC7jZHmebCZBC15IZWRIfWZtP1ExlB0seH6KUlw9ZkztoDpUumuWKWT5WlT9KdRj/bQVKIS6L2wgtGFFwKiFrWiDuzO+mOmRzjRGd+9e/ncLVYhD09IHGLvLWmf249O5CKUpmEX/U0Kpw2NuG8XqLbRGrTWUzPcBi555Q2gVbM1QclzFcNjJT0X+/rpa+tTFPNhwDMh5fp4d6ab1LLvf+/JkH4O7doZO+1OqunPA+zvnRRFxZQ2lixVohxTy+v3SpbCeOZqvvCRivhRafI1uKCWXXPoJ5pFHTyeRmbQsQA4jKYGgYqsGb3SYN56qwCrF9dQgavBkSOOj75NwyP8KdrpDv7YCVnYbXU8=
deploy:
  provider: releases
  api_key:
    secure: FE4XX3/kKWtf56KA+dqO/X9FVDW1iZEynAYdgiF+yCu0D1is5ehcWRP9Nk+9jtQn4vpwCtKPmllwX85wIHYYO8ulb6qsr7uWh8rQ4NQPfCBk2ClCwdh7LrqhzR1HU3jnYg7JsmascjDlPn02ym7vrdXP4I8KVpSAQ1ZOdKjMYH9FiqL3u9JXrlMjBGHRdlsEwgEQN0txLwHocVNYlg4DRcFLQfqHQE6MDsNBhj7rHtHkniHS/ICjtZ+syRGsFK5TCqiQV/pqoGtjsSUN0hpesqPV7FFiKOAyOO3ZPhV6Ph6peEawPWd/tBbG/5XYfnqfH3DbzVJOowMVvGJVdYzefMeZn0TidcjjV2nU/bvq6X0aXYhfaLxU604i3Ph2Qw58Yb57cQZefJFhUxz4OuKkbmtr52P+4GubmdTxy1mSaaCOISerKCsdsaQv/yYJ0n+seutuTtIFM9OB8DjL1d9iykdZe+KN5BUJGqtpMfzCcCafQibysATx/5UybtIpjWjiLYVdWvxMNn09LPsOTjiHNRKoX/95DsJHHROX4IyXjRe0k7z5IRLTGRyymAOyX5SBt0sClfYIICyc755oX3DrWuFa1MZOd8EmSpY+V064YV4IHoNlph+LKNoBiE3NYftBIuSg3a1G+LJN5hNWdw0fWAdud/2/PB4Al4A7owzvmbA=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: xebialabs-community/xlr-cloudforms-plugin
