language: java
notifications:
  hipchat:
    rooms:
      secure: l+qFKnfFcysPPPwftNvTYVUqQNkAPez+9xZB62S38Y6F6wtDSq+ROQE5nFCCT1F6g2qFY/kuZOQvXmBF6ohS+9ShSVcxvuyCgw2/WQgWKMkrQGKrZmYfki3Vmm9HpPFFOfVhzdgHluaN4MxZbaJFNzI/hdqJRUYzg69J6hpYA+j8hPnLnAk2Y6t+UvCtEo0g7wmRDbrtHyxq9MTwhYQxJyTjJKaIX5hb1d4ZlJxOwB6MR/kJThFSdFrd8UWrLtUb5hAyJzOZWodHsurNz/1mPOnH7WhuUaz6yhKsnprN5vTalQRa/qNIgnBLk1uPCKiRTzYXdiuEZC7jZHmebCZBC15IZWRIfWZtP1ExlB0seH6KUlw9ZkztoDpUumuWKWT5WlT9KdRj/bQVKIS6L2wgtGFFwKiFrWiDuzO+mOmRzjRGd+9e/ncLVYhD09IHGLvLWmf249O5CKUpmEX/U0Kpw2NuG8XqLbRGrTWUzPcBi555Q2gVbM1QclzFcNjJT0X+/rpa+tTFPNhwDMh5fp4d6ab1LLvf+/JkH4O7doZO+1OqunPA+zvnRRFxZQ2lixVohxTy+v3SpbCeOZqvvCRivhRafI1uKCWXXPoJ5pFHTyeRmbQsQA4jKYGgYqsGb3SYN56qwCrF9dQgavBkSOOj75NwyP8KdrpDv7YCVnYbXU8=
deploy:
  provider: releases
  api_key:
    secure: dGAf9XGpMyvEzdFdKXHRc2RjixDQROA9rKEFYrV8QYbG8cQN3ZyJd9CVJ56fwCUrP94ua7rXUHPhpkWAzUCO7GI0DOHLhUkBL/aV1Kji9EljrjjPVxe6ET7yweknpMtx4ZUhZ3l9DrC0I0Dh5KGc9wSR0Kk28Mo+eM6QXFnAA8fJd3zevIzbv4HbEwh0Joqh4NPQF22TFzghLzCHyGUtvhmarTp12v991r9mDTXFv6EkdSKk2CePqMQd+FEciOXgxOaD8cXWANL3XNmzV+7iwxgebLmpr8Jvjf2Qkat5Hv6Y5rotD4FRkNfPCYKCzSXoxHfulDy0/CyhJHtlr1e49z0VieIsEVzDuPSkSar1LXNnEHkSKLhL9eMomFiDrY3rmkjg2LWBaCNj8u3/wEWklpkexpJckkAFnAd2sGQdSzDDos/LrqeK78jLlNqJdriH12fma7OWKYiiuZ9ZsDioiOO9aTJHFUBTdRXiv7lNErQVjfRMFm3X4swoeS1CqsIjQacdoil2Bv5eUIDtCaqM6Jit9Z5glgq2qaotTm3bacJHNonSaLn7VosmQL0FUDd8u/GYyJfAbls6uPSEEXNwNTvxOzWDN5s+EwAN198taAvC5RyCGAyADZoLhxGIg0AeqoqYrZoB+vdO5Rtn+z1PFkVloirTP4zByhu+EPhg7jg=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: xebialabs-community/xlr-cloudforms-plugin
